; PROJECT_NAME

RELEASE_DSK    = 1
RELEASE_TAPE   = 1


; CPC+ ASIC registers are paged to the range #4000-#7fff.
; The code should not be in that range when using CPC+ features.
  org #8000

progBegin

progEnd

save"build/PROJECT_NAME.bin",progBegin,progEnd-progBegin

if RELEASE_DSK
save"PROJECT_NAME.bin",progBegin,progEnd-progBegin,DSK,"build/PROJECT_NAME.dsk"
endif

if RELEASE_TAPE
save"PROJECT_NAME.bin",progBegin,progEnd-progBegin,TAPE,"build/PROJECT_NAME.cdt"
endif
