#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    terminal_cursor_shape = 1
    relativenumber = false

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "checkers"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "debug"

[[layers]]
  name = "denite"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "git"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "test"

[[layers]]
  name = "lsp"
  filetypes = [
#    "java",
    "rust",
    "go",
    "python",
    "c",
    "cpp",
    "sh",
    "html",
    "dockerfile",
    "javascript"
  ]
  [layers.override_cmd]
    go = ["gopls"]
    rust = ["rust-analyzer"]
#    java = [
#      "java",
#      "-Declipse.application=org.eclipse.jdt.ls.core.id1",
#      "-Dosgi.bundles.defaultStartLevel=4",
#      "-Declipse.product=org.eclipse.jdt.ls.core.product",
#      "-Dlog.protocol=true",
#      "-Dlog.level=NONE",
#      "-noverify",
#      "-Xmx1G",
#      "-jar",
#      "~/devel/jdt-lsp/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar",
#      "-configuration",
#      "~/devel/jdt-lsp/config_linux",
#      "-data",
#      "~/.cache/javalsp"
#    ]

[[custom_plugins]]
  name = "jceb/vim-orgmode"
  merged = false
