#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  #colorscheme = "base16-onedark"
  #background = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_display_mode = false

[[layers]]
  name = "colorscheme"
  [options]
    colorscheme = "base16-one-light"
    colorscheme_bg = "light"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "smart"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

#[[layers]]
#  name = "lsp"
#  filetypes = [
#    "rust",
#    "javascript",
#    "python",
#    "c",
#    "cpp",
#    "go"
#  ]
#  [layers.override_cmd]
#    rust = ["rustup", "run", "nightly", "rls"]


[[layers]]
  name = "VersionControl"

[[layers]]
  name = "cscope"

[[layers]]
  name = "debug"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "incseaerch"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#clojure"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name =  "lang#json"

[[layers]]
  name = "lang#lisp"

[[layers]]
  name =  "lang#lua"

[[layers]]
  name =  "lang#markdown"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#go"


# Custom plugins
[[custom_plugins]]
  name = "chriskempson/base16-vim"
  merged = 0

