#!/usr/bin/env bash
IMAGE=~/.local/tmp/i3lock.png
LOCK=~/dotfiles/res/lock.png

lock_pid=$(pgrep i3lock)

if [ -n $lock_pid ]; then
	#sleep 0.1 && scrot $IMAGE
	RES=$(xrandr --current | grep "\*" | cut -d ' ' -f 4)
	BG=$(grep feh ~/.fehbg | cut -f 3 -d ' ' | tr -d "'")
	##convert -scale 5% -scale 2000% $IMAGE $IMAGE
	convert $BG -resize $RES^ -gravity Center -extent $RES -blur 0x5 $IMAGE
	convert -composite -gravity center -depth 8 $IMAGE $LOCK $IMAGE
	i3lock -t -e -c 282c34 -i $IMAGE
fi

