#!/usr/bin/env bash
IMAGE=~/.local/tmp/i3lock.png
LOCK=~/dotfiles/res/lock.png

lock_pid=$(pgrep i3lock)

if [ -n $lock_pid ]; then
	mkdir -p ~/.local/tmp > /dev/null 2>&1
	cd ~/.local/tmp
	sleep 0.1 && scrot $IMAGE
	convert -scale 5% -scale 2000% -blur 0x5 $IMAGE $IMAGE
	convert -composite -gravity center -depth 8 $IMAGE $LOCK $IMAGE
	rm -f tile*
	i3lock -t -e -c 282c34 -i $IMAGE
fi

