#!/usr/bin/env bash
locker='swaylock -f -c 000000'
session_logout='swaymsg exit'

if [ $XDG_SESSION_DESKTOP == "i3" ]; then
	locker='xset s activate'
	session_logout='i3-msg exit'
fi
 
question=$(echo "  Lock| Logout| Suspend| Reboot| Shutdown" | rofi -sep "|" \
    -dmenu -i -p 'System: ' "" -width 20 -lines 5)

case $question in
    *Lock)
        $locker
        ;;
    *Logout)
        $session_logout
        ;;
    *Suspend)
        systemctl suspend
        ;;
    *Reboot)
        systemctl reboot
        ;;
    *Shutdown)
        systemctl poweroff
        ;;
    *)
        :  # do nothing on wrong response
        ;;
esac
